### ISSUE TITLE
provide JS export of icon groupings...

### ISSUE THREAD

**Issue by chantastic** [planningcenter/icons#43]
Chatting with @jonsuh about how their migration to v7 went, we were discussing the challenge of locating certain icons.

For example, dynamic code like this makes it difficult to find specific usages of icons:
```
productName => <Symbol use={`product#{productName}-logomark`} />
```

An app could bypass this issue by creating an intermediate mapping:
```
export const productLogomarks = {
  "calendar": "product#calendar-logomark",
  "check-ins": "product#check-ins-logomark",
  ...
}

productName => <Symbol use={productLogomarks[productName]} />
```

This is hard to *enforce* in apps.
So, we thought a way to *encourage* it might be to export critical mappings with the library.

Thoughts?

**Comment by jonsuh** [comment]
While there were some icons that weren’t as easy to find, the ones I missed after the first pass flew under the radar because no error was thrown when an icon didn’t exist in the upgraded library.

Would intermediate mapping be necessary if we just wanted the icon to throw an error if it doesn’t exist? An error doesn’t solve the problem of making icons easier to find when looking for them, but at least warns us that there’s an invalid icon.

**Comment by chantastic** [comment]
Good question.
Right now we're using strings. And there's no good way to statically analyze the use of individual icons — with certainty.

If each icon were individually imported thru JS modules, maybe. But I think there are worse maintenance concerns to worry about with that path — like code not being easily transported between environments and icons not being cached by the browser.
